from random import randint
import webbrowser
import tkinter as tk
import time
from tkinter import ttk

chrome_path = 'open -a /Applications/Google\ Chrome.app %s'

verbs_list = [
    "être",
    "avoir",
    "faire",
    "pouvoir",
    "aller",
    "devoir",
    "dire",
    "voir",
    "prendre",
    "savoir",
    "mettre",
    "vouloir",
    "trouver",
    "donner",
    "venir",
    "passer",
    "falloir",
    "permettre",
    "utiliser",
    "penser",
    "comprendre",
    "rester",
    "connaître",
    "partir",
    "jouer",
    "aimer",
    "demander",
    "parler",
    "arriver",
    "devenir",
    "laisser",
    "rendre",
    "commencer",
    "offrir",
    "tenir",
    "proposer",
    "attendre",
    "croire",
    "suivre",
    "sembler",
    "obtenir",
    "vivre",
    "créer",
    "agir",
    "présenter",
    "sortir",
    "regarder",
    "aider",
    "concerner",
    "porter",
    "choisir",
    "retrouver",
    "perdre",
    "entendre",
    "écrire",
    "montrer",
    "appeler",
    "répondre",
    "recevoir",
    "chercher",
    "continuer",
    "découvrir",
    "gagner",
    "travailler",
    "lire",
    "décider",
    "changer",
    "réaliser",
    "poser",
    "assurer",
    "sentir",
    "revenir",
    "compter",
    "exister",
    "finir",
    "acheter",
    "apprendre",
    "souhaiter",
    "ajouter",
    "expliquer",
    "servir",
    "ouvrir",
    "produire",
    "oublier",
    "considérer",
    "lancer",
    "fournir",
    "annoncer",
    "arrêter",
    "importer",
    "prévoir",
    "développer",
    "garder",
    "atteindre",
    "organiser",
    "rencontrer",
    "tomber",
    "reconnaître",
    "apporter",
    "reprendre",
    "rappeler",
    "profiter",
    "envoyer",
    "éviter",
    "représenter",
    "espérer",
    "tourner",
    "situer",
    "installer",
    "entrer",
    "lier",
    "tenter",
    "participer",
    "mener",
    "indiquer",
    "augmenter",
    "accepter",
    "constituer",
    "placer",
    "élever",
    "apparaître",
    "effectuer",
    "déclarer",
    "partager",
    "réduire",
    "réussir",
    "occuper",
    "tirer",
    "publier",
    "mourir",
    "remettre",
    "vendre",
    "préparer",
    "monter",
    "naître",
    "préférer",
    "établir",
    "quitter",
    "manquer",
    "manger",
    "posséder",
    "contenir",
    "engager",
    "associer",
    "toucher",
    "intéresser",
    "améliorer",
    "paraître",
    "accompagner",
    "disposer",
    "traiter",
    "conduire",
    "soutenir",
    "inscrire",
    "valoir",
    "imposer",
    "terminer",
    "suffire",
    "empêcher",
    "viser",
    "adapter",
    "noter",
    "former",
    "protéger",
    "charger",
    "marquer",
    "battre",
    "avancer",
    "tuer",
    "appliquer",
    "fonctionner",
    "rentrer",
    "composer",
    "rejoindre",
    "inviter",
    "poursuivre",
    "cacher",
    "affirmer",
    "rechercher",
    "retourner",
    "refuser",
    "diriger",
    "respecter",
    "estimer",
    "relever",
    "limiter",
    "imaginer",
    "exprimer",
    "fixer",
    "confirmer",
    "révéler",
    "signifier",
    "lever",
    "maintenir",
    "observer",
    "gérer",
    "baser",
    "pousser",
    "intégrer",

]

num2 = 0
limit = 1

root = tk.Tk()
root.title("random verbs")
    
def callback():
    verb = verbs_list[randint(0, 198)]

    webbrowser.get(chrome_path).open(f"https://www.google.com/search?q={verb}+pass%C3%A9+simple")
    time.sleep(120)
    t1 = ttk.Label(root).pack()
    t1 = ttk.Label(root).pack()
    t1 = ttk.Label(root, text=f"New verb = {verb}").pack()
    button1 = ttk.Button(root, text="press if finished", command=callback).pack()
    
while num2 < limit:
    rand_verb = verbs_list[randint(0, 198)]
    label1 = ttk.Label(root, text=f"Verb = {rand_verb}").pack()
    button1 = ttk.Button(root, text="press if finished", command=callback).pack()
    
    num2 += 1
    
    root.mainloop()
