sources_numero_0 = ['https://phys.org/news/2014-12-universe-dimensions.html', 'Matt Williams']
sources_numero_1 = ['https://simple.wikipedia.org/wiki/Dimension', 'Contributors to Wikimedia projects']
sources_numero_2 = ['https://www.youtube.com/watch?v=Dm_d_nUTfmU&ab_channel=CenterofMath', 'Center of Math']
sources_numero_3 = ['https://simple.wikipedia.org/wiki/Euclidean_space', 'Contributors to Wikimedia projects']
sources_numero_4 = ['https://www.britannica.com/science/Euclidean-space', 'The Editors of Encyclopaedia Britannica']
sources_numero_7 = ['https://simple.wikipedia.org/wiki/One-dimensional_space', 'Contributors to Wikimedia projects']
sources_numero_8 = ['https://en.wikipedia.org/wiki/One-dimensional_space', 'Contributors to Wikimedia projects']
sources_numero_9 = ['https://www.youtube.com/watch?v=MV47Mcmo25I&ab_channel=10thdim', '10thdim']
sources_numero_10 = ['https://www.wikiwand.com/en/One-dimensional_space', 'unknown']
sources_numero_11 = ['https://www.math.net/1d', 'unknown']
sources_numero_12 = ['https://en.wikipedia.org/wiki/Cartesian_coordinate_system#/media/File:Cartesian-coordinate-system.svg', 'Contributors to Wikimedia projects']
sources_numero_13 = ['https://en.wikipedia.org/wiki/Two-dimensional_space', 'Contributors to Wikimedia projects']
sources_numero_14 = ['https://www.mathdoubts.com/two-dimensional-space/', 'unknown']
sources_numero_15 = ['https://www.dreamstime.com/stock-illustration-d-coordinate-axis-vector-image-white-image67829314', 'unknown']
sources_numero_16 = ['https://simple.wikipedia.org/wiki/3D', 'Contributors to Wikimedia projects']
sources_numero_17 = ['https://simple.wikipedia.org/wiki/Solid_geometry', 'Contributors to Wikimedia projects']
sources_numero_19 = ['https://acoem.us/blog/other-topics/x-y-z-axis-stand/', 'unknown']
sources_numero_20 = ['https://simple.wikipedia.org/wiki/Cartesian_coordinate_system', 'Contributors to Wikimedia projects']
sources_numero_21 = ['https://mathinsight.org/cartesian_coordinates', 'unknown']
sources_numero_22 = ['https://www.scienceabc.com/pure-sciences/what-exactly-is-a-tesseract-real-life-geometry-4-dimensional.html', 'unknown']
sources_numero_23 = ['https://www.youtube.com/watch?v=j-ixGKZlLVc&ab_channel=TheScienceElf', 'The Science Elf']
sources_numero_25 = ['https://interestingengineering.com/understanding-fourth-dimension-3d-perspective', 'unknown']
sources_numero_29 = ['https://en.wikipedia.org/wiki/Immersion_(mathematics)', 'Contributors to Wikimedia projects']
sources_numero_30 = ['https://www.scienceabc.com/pure-sciences/what-exactly-is-a-tesseract-real-life-geometry-4-dimensional.html', 'unknown']
sources_numero_31 = ['https://en.wikipedia.org/wiki/Klein_bottle', 'Contributors to Wikimedia projects']
sources_numero_32 = ['https://www.smithsonianmag.com/science-nature/mathematical-madness-mobius-strips-and-other-one-sided-objects-180970394/', 'David Gunderman and Richard Gunderman The Conversation']
sources_numero_33 = ['https://en.wikipedia.org/wiki/M%C3%B6bius_strip', 'Contributors to Wikimedia projects']
sources_numero_34 = ['https://www.youtube.com/watch?v=2s4TqVAbfz4&ab_channel=Numberphile', 'Numberphile']
sources_numero_35 = ['https://en.wikipedia.org/wiki/8-cube', 'Contributors to Wikimedia projects']
sources_numero_36 = ['https://phys.org/news/2014-12-universe-dimensions.html', 'unknown']
sources_numero_37 = ['https://www.universetoday.com/48619/a-universe-of-10-dimensions/', 'unknown']
sources_numero_38 = ['https://www.youtube.com/watch?v=dr2sIoD7eeU&ab_channel=ZachStar', 'Zach Star']
sources_numero_39 = ['https://www.artstation.com/arnaud_imobersteg', 'unknown']
sources_numero_40 = ['https://www.artstation.com/artwork/QzDQod', 'unknown']
sources_numero_41 = ['https://www.artstation.com/insideitall', 'unknown']
sources_numero_42 = ['https://www.artstation.com/artwork/3oYbvD', 'unknown']
sources_numero_43 = ['https://sebbas.org/', 'Sebastián Barschkis']
sources_numero_45 = ['https://docs.blender.org/manual/en/latest/physics/fluid/introduction.html#liquid-simulations', 'unknown']
sources_numero_46 = ['https://www.artstation.com/artificial3d', 'unknown']
sources_numero_48 = ['https://en.bandainamcoent.eu/elden-ring/elden-ring', 'unknown']
sources_numero_49 = ['https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.xboxygen.com%2FNews%2F40029-Ventes-de-Elden-Ring-carton-plein-aux-Etats-Unis-premier-sur-Xbox-en-fevrier&psig=AOvVaw2owQEsFk73anN5N9vMVEVB&ust=1649931945712000&source=images&cd=vfe&ved=0CAoQjRxqFwoTCJiL1dDpkPcCFQAAAAAdAAAAABAs', 'unknown']
sources_numero_50 = ['https://hitman.com/global/', 'unknown']
sources_numero_51 = ['https://www.google.com/url?sa=i&url=https%3A%2F%2Fbit-tech.net%2Ffeatures%2Fgaming%2Fpc%2Fhitman-3-review%2F1%2F&psig=AOvVaw2Rltb2vpHILyPVixbeblgg&ust=1649932203022000&source=images&cd=vfe&ved=0CAoQjRxqFwoTCKjAkMvqkPcCFQAAAAAdAAAAABAD', 'unknown']
sources_numero_52 = ['https://en.wikipedia.org/wiki/3D_modeling', 'Contributors to Wikimedia projects']
sources_numero_53 = ['https://www.youtube.com/watch?v=TEAtmCYYKZA&ab_channel=CrashCourse', 'CrashCourse']
sources_numero_54 = ['https://en.wikipedia.org/wiki/3D_computer_graphics', 'Contributors to Wikimedia projects']
sources_numero_55 = ['https://www.sciencedaily.com/terms/3d_computer_graphics.htm', 'unknown']
sources_numero_56 = ['https://www.quora.com/How-do-3D-graphics-work', 'unknown']
sources_numero_57 = ['https://www.khanacademy.org/computing/computer-programming/programming-games-visualizations/programming-3d-shapes/a/what-are-3d-shapes', 'unknown']
sources_numero_58 = ['https://www.techtarget.com/whatis/definition/3D-mesh', 'TechTarget Contributor']
sources_numero_59 = ['https://www.khanacademy.org/computing/pixar/rendering/rendering1/v/rendering-2', 'unknown']
sources_numero_61 = ['https://unity.com/srp/universal-render-pipeline', 'Unity Technologies']
sources_numero_62 = ['https://www.realtimerendering.com/', 'unknown']
sources_numero_63 = ['https://www.marxentlabs.com/3d-rendering/', 'unknown']
sources_numero_65 = ['https://en.wikipedia.org/wiki/3D_computer_graphics', 'Contributors to Wikimedia projects']
sources_numero_66 = ['https://en.wikipedia.org/wiki/3D_projection', 'Contributors to Wikimedia projects']
sources_numero_67 = ['https://en.wikipedia.org/wiki/Rendering_(computer_graphics)', 'Contributors to Wikimedia projects']
sources_numero_68 = ['https://www.youtube.com/watch?v=TEAtmCYYKZA&ab_channel=CrashCourse', 'CrashCourse']
sources_numero_69 = ['https://www.kmjn.org/notes/3d_rendering_intro.html', 'unknown']
sources_numero_70 = ['https://techterms.com/definition/wireframe', 'unknown']
sources_numero_71 = ['https://www.kmjn.org/notes/3d_rendering_intro.html', 'unknown']
sources_numero_74 = ['https://sciencing.com/split-triangle-fourths-8487469.html', 'unknown']
sources_numero_75 = ['https://www.youtube.com/watch?v=cH_NaCkrkAM&ab_channel=eHowEducation', 'eHowEducation']
sources_numero_76 = ['https://en.wikipedia.org/wiki/Polygon_mesh', 'Contributors to Wikimedia projects']
sources_numero_77 = ['https://en.wikipedia.org/wiki/Convex_polygon', 'Contributors to Wikimedia projects']
sources_numero_79 = ['https://developer.nvidia.com/discover/ray-tracing', 'unknown']
sources_numero_80 = ['https://cs.stanford.edu/people/eroberts/courses/soco/projects/1997-98/ray-tracing/types.html', 'unknown']
sources_numero_81 = ['https://www.khanacademy.org/computing/pixar/rendering/rendering1/v/rendering-1', 'unknown']
sources_numero_82 = ['https://www.khanacademy.org/computing/pixar/rendering/rendering1/e/light-rays', 'unknown']
sources_numero_83 = ['https://www.khanacademy.org/computing/pixar/rendering/rendering1/v/render-4', 'unknown']
sources_numero_84 = ['https://viclw17.github.io/2018/06/30/raytracing-rendering-equation', 'Victor Li']
sources_numero_86 = ['https://en.wikipedia.org/wiki/Rendering_equation', 'Contributors to Wikimedia projects']
sources_numero_87 = ['https://www.youtube.com/watch?v=AODo_RjJoUA', 'NVIDIA Developer']
sources_numero_88 = ['https://viclw17.github.io/2018/07/15/raytracing-image-output', 'Victor Li']
sources_numero_89 = ['https://viclw17.github.io/2018/07/20/raytracing-diffuse-materials', 'Victor Li']
sources_numero_90 = ['https://www.youtube.com/watch?v=0J8tKGjEE5Q', 'Sebastian Lague']
sources_numero_92 = ['https://en.wikipedia.org/wiki/Ray_tracing_(graphics)#Algorithm_overview', 'Contributors to Wikimedia projects']
sources_numero_93 = ['https://lodev.org/cgtutor/raycasting.html', 'unknown']
sources_numero_94 = ['https://www.techopedia.com/definition/21614/ray-casting', 'Techopedia']
sources_numero_95 = ['https://www.youtube.com/watch?v=ll4_79zKapU', 'Bob Laramee']
sources_numero_96 = ['https://en.wikipedia.org/wiki/Ray_casting', 'Contributors to Wikimedia projects']
sources_numero_100 = ['https://www.researchgate.net/publication/321125112_Daylight_simulation_with_photon_maps', 'Roland Schregle']
sources_numero_102 = ['https://inspirationtuts.com/blender-render-engines-free-options-included/', "InspirationTuts"]
sources_numero_105 = ['https://archicgi.com/cgi-news/3d-render-engines-choosing-the-best/', "ArchiCGI"]
sources_numero_107 = ['https://www.youtube.com/watch?v=qJEWOTZnFeg', "Blender Guru"]
sources_numero_108 = ['https://www.youtube.com/watch?v=pEvMJYzLTuE', "Blender Guru"]
sources_numero_109 = ['https://www.youtube.com/watch?v=-SOP2YYRKss', 'Blender Guru']
sources_numero_110 = ['https://www.youtube.com/watch?v=-SOP2YY', 'unknown']
sources_numero_111 = ['https://www.geospatialworld.net/article/5-industrial-applications-of-3d-printing-services', 'Wayken Rapid']
sources_numero_112 = ['https://markforged.com/resources/blog/five-industries-utilizing-3d-printing', 'unknow']
sources_numero_114 = ['https://cprimestudios.com/blog/how-3d-printing-used-automotive-industry', 'Cprime Studios']
sources_numero_115 = ['https://xometry.eu/en/application-of-3d-printing-in-automotive-industry/', 'Evgeny Misnikov']
sources_numero_116 = ['https://www.agh.edu.pl/en/science/info/article/rte-20-lem-agh-racing-team-introduce-their-new-electric-racing-car/', 'unknown']
sources_numero_118 = ['https://cobod.com/', 'unknown']
sources_numero_119 = ['https://www.iconbuild.com/', 'unknown']
sources_numero_120 = ['https://all3dp.com/2/best-companies-building-3d-printed-houses/', 'ALL3DP']
sources_numero_121 = ['https://www.peri.com/en/media/press-releases/germanys-first-printed-house-officially-openend.html', 'unknown']
sources_numero_122 = ['https://www.gira.com/uk/en/inspirations/references/3d-house-germany', 'unkown']
sources_numero_123 = ['https://www.techadvisor.com/feature/small-business/5-top-uses-of-3d-printing-3788919/', 'Tech Advisor']
sources_numero_124 = ['https://www.makepartsfast.com/3d-printed-circuit-boards-how-theyre-made-and-why-they-matter/', 'Leslie Lagna']
sources_numero_125 = ['https://en.wikipedia.org/wiki/Fused_filament_fabrication', 'Contributors to Wikimedia projects']
sources_numero_126 = ['https://all3dp.com/2/pcb-3d-printer-all-about-3d-printed-circuit-boards/', 'Henry Haefliger']
sources_numero_127 = ['https://maker.pro/pcb/tutorial/how-to-make-a-printed-circuit-board-pcb', 'Suraj Gehlot']
sources_numero_128 = ['https://en.wikipedia.org/wiki/Printed_circuit_board', 'Contributors to Wikimedia projects']
sources_numero_129 = ['https://www.eurocircuits.com/pcb-printed-circuit-board/', 'unknown']
sources_numero_130 = ['https://www.pcbway.com/rapid-prototyping/3D-Printing/3D-Printing-FDM.html', 'unknown']
sources_numero_131 = ['https://all3dp.com/2/what-is-material-jetting-3d-printing-simply-explained/', 'Leo Gregurić']
sources_numero_132 = ['https://www.hubs.com/knowledge-base/introduction-material-jetting-3d-printing/', 'Alkaios Bournias Varotsis']
sources_numero_133 = ['https://www.cnet.com/pictures/this-3d-printed-mars-habitat-could-be-your-new-home-in-space-marsha-ai-spacefactory/', 'Claire Reilly']
sources_numero_134 = ['https://www.nasa.gov/mission_pages/station/research/news/3d-printing-in-space-long-duration-spaceflight-applications/', 'Michael Johnson']
sources_numero_135 = ['https://www.3dnatives.com/en/top-10-3d-printing-space/', "3Dnatives"]
sources_numero_138 = ['https://www.aispacefactory.com/ ', 'aispacefactory']
sources_numero_139 = ['https://www.youtube.com/watch?v=34DfBw6c10o', 'SpaceFactory']
sources_numero_140 = ['https://interestingengineering.com/10-surprising-ways-3d-printing-is-being-used-now', 'Ariella Brown']
sources_numero_143 = ['https://www.prusaprinters.org/prints/122320-one-for-all-cable-strap-print-in-place-clamp/', 'Extrutim']
sources_numero_151 = ['https://www.fabbaloo.com/news/design-of-the-week-mechanical-wall-clock/', 'Kerry Stevenson']
sources_numero_153 = ['https://www.voxelab3dp.com/product/aquila-diy-fdm-3d-printer/', 'Voxellab3dp']
sources_numero_154 = ['https://www.tomshardware.com/reviews/voxelab-aquila-x2-3d-printer/', "Voxelab Aquila X2"]
sources_numero_155 = ['https://3dprinterly.com/voxelab-aquila-x2-review/', '3D printerly']
sources_numero_156 = ['https://total3dprinting.org/voxelab-aquila-review/', "Justin Cadwell"]
sources_numero_157 = ['https://www.creality.com/goods-detail/ender-3-v2-3d-printer/', 'Creality']
sources_numero_158 = ['https://www.creality.com/goods-detail/ender-3-v2-3d-printer/', 'Creality']
sources_numero_159 = ['https://www.pcmag.com/reviews/creality-ender-3-v2/', "PCMag"]
sources_numero_160 = ['https://all3dp.com/1/creality-ender-3-v2-review-3d-printer-specs/', 'Anatol Locker']
sources_numero_161 = ['https://3dprinterly.com/creality-ender-3-v2-review-worth-it-or-not/', '3D printerly']
sources_numero_165 = ['https://www.3dbeginners.com/prusa-i3-mk2-review/', 'Justin Evans']
sources_numero_166 = ['https://www.tomshardware.com/reviews/prusa-mk3s-plus-3d-printer-review/', "Andrew Sink"]
sources_numero_167 = ['https://makershop.co/prusa-i3-mk3s-review/', "MakerShop"]
sources_numero_170 = ['https://www.youtube.com/watch?v=Vx0Z6LplaMU', "Mashable"]
sources_numero_172 = ['https://www.myminifactory.com/', 'myminifatory']
sources_numero_174 = ['https://en.wikipedia.org/wiki/G-code', 'Contributors to Wikimedia projects']
sources_numero_178 = ['https://all3dp.com/1/types-of-3d-printers-3d-printing-technology/', 'ALL3DP']
sources_numero_179 = ['https://all3dp.com/2/connecting-to-your-ender-3-via-usb/', 'Pranav Gharge']
sources_numero_180 = ['https://www.ge.com/additive/additive-manufacturing', 'unknown']
sources_numero_181 = ['https://www.hubs.com/knowledge-base/what-is-fdm-3d-printing/', 'Alkaios Bournias Varotsis, Isaac Simon']
sources_numero_182 = ['https://all3dp.com/2/fused-deposition-modeling-fdm-3d-printing-simply-explained/', 'Emmett Grames']
sources_numero_183 = ['https://www.hubs.com/knowledge-base/what-is-sla-3d-printing/', "Alkaios Bournias Varotsis"]
sources_numero_185 = ['https://formlabs.com/eu/store/form-3-basic-package-without-service/', 'formlabs']
sources_numero_186 = ['https://all3dp.com/2/clean-3d-print-bed-3d-printer/', 'Jackson Moody']
sources_numero_187 = ['https://www.thespaghettidetective.com/docs/octoprint-plugin-setup/', 'unknown']
sources_numero_188 = ['https://www.thespaghettidetective.com/', "The Spaghetti Detective"]
sources_numero_189 = ['https://www.thespaghettidetective.com/blog/2021/12/16/3d-printer-issues-and-how-to-troubleshoot-them/', 'unknown']
sources_numero_190 = ['https://all3dp.com/1/common-3d-printing-problems-troubleshooting-3d-printer-issues/', 'unknown']
sources_numero_191 = ['https://www.simplify3d.com/support/print-quality-troubleshooting/stops-extruding-mid-print/', "unknown"]
